# Generated by Django 5.2.6 on 2025-09-17 14:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('fastfoodapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rating',
            new_name='review',
        ),
    ]
