# Generated by Django 5.2.6 on 2025-09-23 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0003_alter_product_options_product_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RemoveField(
            model_name='product',
            name='position',
        ),
    ]
