# Generated by Django 5.2.6 on 2025-09-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0005_alter_product_options_product_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
