# Generated by Django 5.2.6 on 2025-09-23 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0006_alter_product_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RemoveField(
            model_name='product',
            name='sort_order',
        ),
    ]
